import Head from 'next/head';
import { Pagination, Products, Search } from '../Components';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <div>
            <h4 className="text-[#3D639D] text-[22px] font-semibold mt-[30px]">
              Оформить заказ
            </h4>
            <div className="h-[50px] flex justify-between w-full mt-5 br-[2px]">
              <Search />
            </div>
            {/* Availible Products */}
            <div className="mt-[30px]">
              <Products />
            </div>
            <div className="w-full flex items-center justify-between mt-[30px]">
              <Pagination />
            </div>
          </div>
    </div>
  );
}
